package br.jus.trf2.temis.crp.model.enm;

public enum CrpParamCfg {
	PESSOA, LOTACAO, TIPO_DE_LOTACAO, CARGO, FUNCAO, ORGAO, PERFIL, SERVICO, PESSOA_OBJETO, LOTACAO_OBJETO,
	CARGO_OBJETO, FUNCAO_OBJETO, ORGAO_OBJETO, SITUACAO;
}
